### ISSUE TITLE
language of cross reference figr function

### ISSUE THREAD

**Issue by nmolanog** [mkoohafkan/kfigr#8]
Is there a way to change the language of the output for figr function?
Instead of producing "table 1" I want to use "tabla 1"

**Comment by mkoohafkan** [comment]
Sure, you can just use `type = "tabla"` rather than `type = "table"` in your code chunk options. The types are completely arbitrary. You can also tell `kfigr::figr` to print only the number via the argument `prefix = FALSE`. See the vignette (not just the output, but the Rmd file itself) for more examples.
